// Admin actions
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_ERROR = 'ADMIN_LOGIN_ERROR';
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';


// User actions
export const SET_USER_LOCATION = 'SET_USER_LOCATION';


// Service actions
export const SERVICE_LOAD_REQUEST = 'SERVICE_LOAD_REQUEST';
export const SERVICE_LOAD_SUCCESS = 'SERVICE_LOAD_SUCCESS';
export const SERVICE_LOAD_ERROR = 'SERVICE_LOAD_ERROR';

export const SERVICES_LOAD_REQUEST = 'SERVICES_LOAD_REQUEST';
export const SERVICES_LOAD_SUCCESS = 'SERVICES_LOAD_SUCCESS';
export const SERVICES_LOAD_ERROR = 'SERVICES_LOAD_ERROR';



export const adminActions = {
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_ERROR: 'ADMIN_LOGIN_ERROR',
    ADMIN_LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST'
}

export const userActions = {
    SET_USER_LOCATION = 'SET_USER_LOCATION'
}

export const serviceActions = {
    SERVICE_LOAD_REQUEST: 'SERVICE_LOAD_REQUEST',
    SERVICE_LOAD_SUCCESS: 'SERVICE_LOAD_SUCCESS',
    SERVICE_LOAD_ERROR: 'SERVICE_LOAD_ERROR',

    SERVICES_LOAD_REQUEST: 'SERVICES_LOAD_REQUEST',
    SERVICES_LOAD_SUCCESS: 'SERVICES_LOAD_SUCCESS',
    SERVICES_LOAD_ERROR: 'SERVICES_LOAD_ERROR'
}

export const categoryActions = {
    CATEGORIES_LOAD_REQUEST: 'CATEGORIES_LOAD_REQUEST',
    CATEGORIES_LOAD_SUCCESS: 'CATEGORIES_LOAD_SUCCESS',
    CATEGORIES_LOAD_ERROR: 'CATEGORIES_LOAD_ERROR',

    FEATURED_CATEGORIES_LOAD_REQUEST: 'FEATURED_CATEGORIES_LOAD_REQUEST',
    FEATURED_CATEGORIES_LOAD_SUCCESS: 'FEATURED_CATEGORIES_LOAD_SUCCESS',
    FEATURED_CATEGORIES_LOAD_ERROR: 'FEATURED_CATEGORIES_LOAD_ERROR'
}

export const resourceActions = {
    RESOURCES_LOAD_REQUEST: 'RESOURCES_LOAD_REQUEST',
    RESOURCES_LOAD_SUCCESS: 'RESOURCES_LOAD_SUCCESS',
    RESOURCES_LOAD_ERROR: 'RESOURCES_LOAD_ERROR',

    RESOURCE_LOAD_REQUEST: 'RESOURCE_LOAD_REQUEST',
    RESOURCE_LOAD_SUCCESS: 'RESOURCE_LOAD_SUCCESS',
    RESOURCE_LOAD_ERROR: 'RESOURCE_LOAD_ERROR',

    VERIFY_RESOURCE_LOAD_REQUEST: 'VERIFY_RESOURCE_LOAD_REQUEST',
    VERIFY_RESOURCE_LOAD_SUCCESS: 'VERIFY_RESOURCE_LOAD_SUCCESS',
    VERIFY_RESOURCE_LOAD_ERROR: 'VERIFY_RESOURCE_LOAD_ERROR'
}

export const eligibilityActions = {
    FEATURED_ELIGIBILITIES_LOAD_REQUEST: 'FEATURED_ELIGIBILITIES_LOAD_REQUEST',
    FEATURED_ELIGIBILITIES_LOAD_SUCCESS: 'FEATURED_ELIGIBILITIES_LOAD_SUCCESS',
    FEATURED_ELIGIBILITIES_LOAD_ERROR: 'FEATURED_ELIGIBILITIES_LOAD_ERROR'
}
