export default {
  ALGOLIA_APPLICATION_ID: CONFIG.ALGOLIA_APPLICATION_ID,
  ALGOLIA_INDEX_PREFIX: CONFIG.ALGOLIA_INDEX_PREFIX,
  ALGOLIA_READ_ONLY_API_KEY: CONFIG.ALGOLIA_READ_ONLY_API_KEY,
  GOOGLE_API_KEY: CONFIG.GOOGLE_API_KEY,
  MOHCD_SUBDOMAIN: CONFIG.MOHCD_SUBDOMAIN,
};
