export default {
  ALGOLIA_APPLICATION_ID: CONFIG.ALGOLIA_APPLICATION_ID,
  ALGOLIA_INDEX_PREFIX: CONFIG.ALGOLIA_INDEX_PREFIX,
  ALGOLIA_READ_ONLY_API_KEY: CONFIG.ALGOLIA_READ_ONLY_API_KEY,
  GOOGLE_API_KEY: CONFIG.GOOGLE_API_KEY,
  MOHCD_SUBDOMAIN: CONFIG.MOHCD_SUBDOMAIN,
  SENTRY_PROJECT_ID: '1291512',
  SENTRY_PUBLIC_KEY: '64ab4b168902441a9e8069bab36849be',
};
